<?php

/**
 * @file
 * Primary module hooks for Cropper image formatter module.
 */

use Drupal\Component\Serialization\Json;

/**
 * Implements hook_preprocess_HOOK().
 */
function cif_preprocess_image(&$variables): void {
  \Drupal::service('cif.manager')->process($variables);
}

/**
 * Implements hook_page_bottom().
 */
function cif_page_bottom(array &$page_bottom): void {
  if (!\Drupal::service('cif.manager')->attachPopup()) {
    return;
  }

  $page_bottom['cif'] = ['#theme' => 'cif_popup'];
}
/**
 * Implements hook_theme().
 */
function cif_theme(): array {
  return [
    'cif_popup' => [
      'variables' => [],
    ],
  ];
}
